services:
  - type: web
    name: laravel-website
    runtime: php
    buildCommand: "composer install && php artisan key:generate"
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    plan: free
    region: oregon
    branch: main
